package main

import "log"

func SeedData() {
	var count int64
	DB.Model(&Place{}).Count(&count)
	if count > 0 {
		log.Println("Database already seeded, skipping")
		return
	}

	log.Println("Seeding database...")

	// --- Chiang Mai places (10) ---
	chiangMaiPlaces := []Place{
		{
			ExternalID:  "cm-doi-suthep",
			Name:        "Doi Suthep",
			Description: "A sacred mountain temple overlooking Chiang Mai, Wat Phra That Doi Suthep is one of northern Thailand's most revered Buddhist sites with stunning panoramic views of the city.",
			Latitude:    18.8048,
			Longitude:   98.9218,
			ImageURL:    "https://picsum.photos/seed/doisuthep/800/600",
			Country:     "Thailand",
			City:        "Chiang Mai",
			Rating:      4.7,
			Tags:        JSONStringSlice{"temple", "mountain", "cultural", "scenic"},
			IsActive:    true,
		},
		{
			ExternalID:  "cm-old-city",
			Name:        "Chiang Mai Old City",
			Description: "The historic heart of Chiang Mai, surrounded by ancient walls and a moat. Home to over 30 temples, local markets, and charming streets perfect for walking and exploring.",
			Latitude:    18.7883,
			Longitude:   98.9853,
			ImageURL:    "https://picsum.photos/seed/cmoldcity/800/600",
			Country:     "Thailand",
			City:        "Chiang Mai",
			Rating:      4.5,
			Tags:        JSONStringSlice{"historical", "cultural", "walking", "temples"},
			IsActive:    true,
		},
		{
			ExternalID:  "cm-night-bazaar",
			Name:        "Chiang Mai Night Bazaar",
			Description: "A bustling night market stretching along Chang Klan Road, offering local handicrafts, street food, clothing, and live entertainment every evening.",
			Latitude:    18.7871,
			Longitude:   98.9936,
			ImageURL:    "https://picsum.photos/seed/cmnightbazaar/800/600",
			Country:     "Thailand",
			City:        "Chiang Mai",
			Rating:      4.3,
			Tags:        JSONStringSlice{"market", "shopping", "nightlife", "food"},
			IsActive:    true,
		},
		{
			ExternalID:  "cm-tha-phae-gate",
			Name:        "Tha Phae Gate",
			Description: "The main entrance to Chiang Mai's Old City and a iconic landmark. The gate area hosts weekend markets, cultural events, and is a popular gathering spot for locals and tourists alike.",
			Latitude:    18.7876,
			Longitude:   98.9937,
			ImageURL:    "https://picsum.photos/seed/thaphaegate/800/600",
			Country:     "Thailand",
			City:        "Chiang Mai",
			Rating:      4.4,
			Tags:        JSONStringSlice{"landmark", "historical", "cultural", "photography"},
			IsActive:    true,
		},
		{
			ExternalID:  "cm-elephant-nature-park",
			Name:        "Elephant Nature Park",
			Description: "An ethical elephant sanctuary and rescue center where visitors can observe and interact with rescued elephants in their natural habitat without riding or performing.",
			Latitude:    19.1760,
			Longitude:   98.7716,
			ImageURL:    "https://picsum.photos/seed/elephantpark/800/600",
			Country:     "Thailand",
			City:        "Chiang Mai",
			Rating:      4.9,
			Tags:        JSONStringSlice{"nature", "animals", "eco-tourism", "adventure"},
			IsActive:    true,
		},
		{
			ExternalID:  "cm-doi-inthanon",
			Name:        "Doi Inthanon National Park",
			Description: "Thailand's highest peak at 2,565 meters, featuring misty cloud forests, stunning twin pagodas, dramatic waterfalls, and cool mountain weather year-round.",
			Latitude:    18.5874,
			Longitude:   98.4868,
			ImageURL:    "https://picsum.photos/seed/doiinthanon/800/600",
			Country:     "Thailand",
			City:        "Chiang Mai",
			Rating:      4.8,
			Tags:        JSONStringSlice{"nature", "mountain", "hiking", "scenic", "national-park"},
			IsActive:    true,
		},
		{
			ExternalID:  "cm-huay-tung-tao",
			Name:        "Huay Tung Tao Lake",
			Description: "A peaceful reservoir surrounded by mountains, popular with locals for picnicking in bamboo huts by the water, swimming, and enjoying fresh grilled chicken and sticky rice.",
			Latitude:    18.8384,
			Longitude:   98.9502,
			ImageURL:    "https://picsum.photos/seed/huaytungtao/800/600",
			Country:     "Thailand",
			City:        "Chiang Mai",
			Rating:      4.4,
			Tags:        JSONStringSlice{"nature", "lake", "relaxation", "food", "local"},
			IsActive:    true,
		},
		{
			ExternalID:  "cm-wat-chedi-luang",
			Name:        "Wat Chedi Luang",
			Description: "A magnificent 14th-century temple in the heart of Chiang Mai's Old City, featuring a massive partially-ruined chedi that once housed the Emerald Buddha.",
			Latitude:    18.7863,
			Longitude:   98.9862,
			ImageURL:    "https://picsum.photos/seed/watchediluang/800/600",
			Country:     "Thailand",
			City:        "Chiang Mai",
			Rating:      4.6,
			Tags:        JSONStringSlice{"temple", "historical", "cultural", "architecture"},
			IsActive:    true,
		},
		{
			ExternalID:  "cm-nimman",
			Name:        "Nimmanhaemin Road (Nimman)",
			Description: "Chiang Mai's trendy neighborhood filled with stylish cafes, boutique shops, art galleries, and co-working spaces. A hub for digital nomads and creatives.",
			Latitude:    18.7980,
			Longitude:   98.9675,
			ImageURL:    "https://picsum.photos/seed/nimman/800/600",
			Country:     "Thailand",
			City:        "Chiang Mai",
			Rating:      4.5,
			Tags:        JSONStringSlice{"cafe", "shopping", "lifestyle", "trendy", "food"},
			IsActive:    true,
		},
		{
			ExternalID:  "cm-mon-cham",
			Name:        "Mon Cham (Mon Jam)",
			Description: "A scenic hilltop with terraced gardens overlooking mountains and valleys. Known for its strawberry fields, flower gardens, and stunning sunrise and sunset views.",
			Latitude:    18.8978,
			Longitude:   98.8594,
			ImageURL:    "https://picsum.photos/seed/moncham/800/600",
			Country:     "Thailand",
			City:        "Chiang Mai",
			Rating:      4.5,
			Tags:        JSONStringSlice{"nature", "scenic", "mountain", "photography", "garden"},
			IsActive:    true,
		},
	}

	// --- Bangkok places (5) ---
	bangkokPlaces := []Place{
		{
			ExternalID:  "bk-grand-palace",
			Name:        "Grand Palace",
			Description: "Thailand's most iconic landmark, a dazzling complex of royal halls, temples, and the sacred Emerald Buddha. A must-visit for its incredible architecture and rich history.",
			Latitude:    13.7500,
			Longitude:   100.4913,
			ImageURL:    "https://picsum.photos/seed/grandpalace/800/600",
			Country:     "Thailand",
			City:        "Bangkok",
			Rating:      4.6,
			Tags:        JSONStringSlice{"palace", "cultural", "historical", "architecture", "landmark"},
			IsActive:    true,
		},
		{
			ExternalID:  "bk-wat-arun",
			Name:        "Wat Arun (Temple of Dawn)",
			Description: "A stunning riverside temple known for its ornate spires decorated with colorful porcelain. One of Bangkok's most photographed landmarks, especially beautiful at sunset.",
			Latitude:    13.7437,
			Longitude:   100.4888,
			ImageURL:    "https://picsum.photos/seed/watarun/800/600",
			Country:     "Thailand",
			City:        "Bangkok",
			Rating:      4.7,
			Tags:        JSONStringSlice{"temple", "cultural", "architecture", "scenic", "photography"},
			IsActive:    true,
		},
		{
			ExternalID:  "bk-chatuchak",
			Name:        "Chatuchak Weekend Market",
			Description: "One of the world's largest outdoor markets with over 15,000 stalls selling everything from vintage clothing to handmade crafts, plants, pets, and delicious street food.",
			Latitude:    13.7999,
			Longitude:   100.5507,
			ImageURL:    "https://picsum.photos/seed/chatuchak/800/600",
			Country:     "Thailand",
			City:        "Bangkok",
			Rating:      4.5,
			Tags:        JSONStringSlice{"market", "shopping", "food", "local"},
			IsActive:    true,
		},
		{
			ExternalID:  "bk-khao-san",
			Name:        "Khao San Road",
			Description: "Bangkok's legendary backpacker street, famous for its vibrant nightlife, cheap eats, quirky shops, and energetic atmosphere that draws travelers from around the world.",
			Latitude:    13.7589,
			Longitude:   100.4974,
			ImageURL:    "https://picsum.photos/seed/khaosan/800/600",
			Country:     "Thailand",
			City:        "Bangkok",
			Rating:      4.2,
			Tags:        JSONStringSlice{"nightlife", "food", "backpacker", "shopping"},
			IsActive:    true,
		},
		{
			ExternalID:  "bk-asiatique",
			Name:        "Asiatique The Riverfront",
			Description: "A large open-air riverside mall combining shopping, dining, and entertainment in a beautifully renovated warehouse district along the Chao Phraya River.",
			Latitude:    13.7046,
			Longitude:   100.5010,
			ImageURL:    "https://picsum.photos/seed/asiatique/800/600",
			Country:     "Thailand",
			City:        "Bangkok",
			Rating:      4.3,
			Tags:        JSONStringSlice{"shopping", "dining", "nightlife", "riverside"},
			IsActive:    true,
		},
	}

	// --- Phuket places (5) ---
	phuketPlaces := []Place{
		{
			ExternalID:  "pk-patong-beach",
			Name:        "Patong Beach",
			Description: "Phuket's most famous beach, known for its golden sand, crystal-clear water, vibrant nightlife on Bangla Road, and wide range of water sports and entertainment.",
			Latitude:    7.8952,
			Longitude:   98.2960,
			ImageURL:    "https://picsum.photos/seed/patongbeach/800/600",
			Country:     "Thailand",
			City:        "Phuket",
			Rating:      4.3,
			Tags:        JSONStringSlice{"beach", "nightlife", "water-sports", "entertainment"},
			IsActive:    true,
		},
		{
			ExternalID:  "pk-old-town",
			Name:        "Phuket Old Town",
			Description: "A charming historical area with colorful Sino-Portuguese architecture, quirky cafes, street art, local museums, and a vibrant Sunday walking street market.",
			Latitude:    7.8847,
			Longitude:   98.3883,
			ImageURL:    "https://picsum.photos/seed/phuketoldtown/800/600",
			Country:     "Thailand",
			City:        "Phuket",
			Rating:      4.5,
			Tags:        JSONStringSlice{"historical", "cultural", "architecture", "photography", "cafe"},
			IsActive:    true,
		},
		{
			ExternalID:  "pk-big-buddha",
			Name:        "Big Buddha",
			Description: "A 45-meter-tall white marble Buddha statue sitting atop Nakkerd Hill, offering breathtaking 360-degree views of the island and the Andaman Sea.",
			Latitude:    7.8278,
			Longitude:   98.3130,
			ImageURL:    "https://picsum.photos/seed/bigbuddha/800/600",
			Country:     "Thailand",
			City:        "Phuket",
			Rating:      4.6,
			Tags:        JSONStringSlice{"landmark", "cultural", "scenic", "photography"},
			IsActive:    true,
		},
		{
			ExternalID:  "pk-phi-phi",
			Name:        "Phi Phi Islands",
			Description: "A stunning archipelago of six islands famous for turquoise waters, dramatic limestone cliffs, vibrant marine life, and the iconic Maya Bay from 'The Beach' movie.",
			Latitude:    7.7407,
			Longitude:   98.7784,
			ImageURL:    "https://picsum.photos/seed/phiphi/800/600",
			Country:     "Thailand",
			City:        "Phuket",
			Rating:      4.8,
			Tags:        JSONStringSlice{"island", "beach", "snorkeling", "nature", "adventure"},
			IsActive:    true,
		},
		{
			ExternalID:  "pk-promthep-cape",
			Name:        "Promthep Cape",
			Description: "The southernmost tip of Phuket, renowned as one of the best sunset viewpoints in Thailand. Features a lighthouse, elephant shrine, and dramatic rocky coastline.",
			Latitude:    7.7590,
			Longitude:   98.3047,
			ImageURL:    "https://picsum.photos/seed/promthepcape/800/600",
			Country:     "Thailand",
			City:        "Phuket",
			Rating:      4.5,
			Tags:        JSONStringSlice{"scenic", "sunset", "photography", "nature", "landmark"},
			IsActive:    true,
		},
	}

	allPlaces := append(chiangMaiPlaces, bangkokPlaces...)
	allPlaces = append(allPlaces, phuketPlaces...)

	for _, place := range allPlaces {
		DB.Create(&place)
	}

	// --- Rewards (4) ---
	rewards := []Reward{
		{
			Name:          "Hotel Discount 20% Off",
			Description:   "Get 20% off your next hotel booking at any partner hotel in Thailand. Valid for stays up to 5 nights.",
			ImageURL:      "https://picsum.photos/seed/hotelreward/400/300",
			CoinCost:      100,
			Category:      "hotel",
			DiscountCode:  "LONQ-HOTEL-20",
			ValidUntil:    "2026-12-31",
			Location:      "All partner hotels in Thailand",
			OriginalPrice: 5000,
		},
		{
			Name:          "Restaurant Voucher 200 THB",
			Description:   "Enjoy a 200 THB voucher at selected partner restaurants. Perfect for trying local cuisines on your travels.",
			ImageURL:      "https://picsum.photos/seed/foodreward/400/300",
			CoinCost:      50,
			Category:      "restaurant",
			DiscountCode:  "LONQ-FOOD-200",
			ValidUntil:    "2026-12-31",
			Location:      "Partner restaurants nationwide",
			OriginalPrice: 200,
		},
		{
			Name:          "Transport Day Pass",
			Description:   "A full-day transport pass covering BTS, MRT, and airport rail link in Bangkok. Travel unlimited for one day.",
			ImageURL:      "https://picsum.photos/seed/transportreward/400/300",
			CoinCost:      75,
			Category:      "transport",
			DiscountCode:  "LONQ-TRANSIT-DAY",
			ValidUntil:    "2026-12-31",
			Location:      "Bangkok BTS/MRT stations",
			OriginalPrice: 150,
		},
		{
			Name:          "Souvenir Shop 15% Off",
			Description:   "Get 15% off at partner souvenir shops. Bring home authentic Thai handicrafts and souvenirs at a discount.",
			ImageURL:      "https://picsum.photos/seed/souvenirreward/400/300",
			CoinCost:      30,
			Category:      "souvenir",
			DiscountCode:  "LONQ-GIFT-15",
			ValidUntil:    "2026-12-31",
			Location:      "Partner souvenir shops in major tourist areas",
			OriginalPrice: 0,
		},
	}

	for _, reward := range rewards {
		DB.Create(&reward)
	}

	log.Println("Database seeded successfully")
}
